In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("johnsmith88/heart-disease-dataset")

print("Path to dataset files:", path)

/Users/kpvarma/PycharmProjects/Heart_Disease_With_Neural_Network/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/kpvarma/.cache/kagglehub/datasets/johnsmith88/heart-disease-dataset/versions/2

Loading Dataset

In [3]:
import pandas as pd
df=pd.read_csv('heart.csv');
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [5]:
df.shape

(1025, 14)

In [6]:
df.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
X=df.drop('target',axis=1)
Y=df['target']

In [8]:
X_encoded=pd.get_dummies(df,columns=['cp','restecg','slope','thal'],drop_first=False)

In [9]:
X_encoded.shape

(1025, 24)

In [10]:
df.shape

(1025, 14)

Creating Model

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_encoded,Y,test_size=0.3,random_state=42)
print('X_train shape:',x_train.shape)
print('X_test shape:',x_test.shape)
print('Y_train shape:',y_train.shape)
print('Y_test shape:',y_test.shape)

X_train shape: (717, 24)
X_test shape: (308, 24)
Y_train shape: (717,)
Y_test shape: (308,)

In [12]:
from sklearn.preprocessing import StandardScaler
normalize=StandardScaler()
x_train[x_train.columns] = normalize.fit_transform(x_train)
x_test[x_test.columns] = normalize.transform(x_test)

In [13]:
x_train.columns

Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'thalach', 'exang', 'oldpeak',
       'ca', 'target', 'cp_0', 'cp_1', 'cp_2', 'cp_3', 'restecg_0',
       'restecg_1', 'restecg_2', 'slope_0', 'slope_1', 'slope_2', 'thal_0',
       'thal_1', 'thal_2', 'thal_3'],
      dtype='object')

Neural Network

In [14]:
n=[24,32,16,8,1]
print("input layer size", n[0])
print("layer 1 size", n[1])
print("layer 2 size", n[2])
print("layer 3 size", n[3])
print("layer 4 size",n[4])

input layer size 24
layer 1 size 32
layer 2 size 16
layer 3 size 8
layer 4 size 1

In [15]:
import numpy as np
W1=np.random.randn(n[1],n[0])
W2=np.random.randn(n[2],n[1])
W3=np.random.randn(n[3],n[2])
W4=np.random.randn(n[4],n[3])
b1=np.random.randn(n[1],1)
b2=np.random.randn(n[2],1)
b3=np.random.randn(n[3],1)
b4=np.random.randn(n[4],1)

In [16]:
print(x_train.shape)

(717, 24)

In [17]:
X_train=x_train.T
print(X_train.shape)

(24, 717)

In [18]:
y_train.shape

(717,)

In [19]:
import numpy as np

y_train = np.array(y_train).reshape(-1, 1)
y_test = np.array(y_test).reshape(-1, 1)

In [20]:
print(y_train.shape)

(717, 1)

In [21]:
def sigmoid(arr):
  return 1 / (1 + np.exp(-1 * arr))

In [22]:
import numpy as np
def relu(x):
    return np.maximum(0, x)

In [23]:
# assuming X_train.shape = (n_features, m)
# W1, b1, W2, b2, etc. are numpy arrays

def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# forward propagation
Z1 = W1 @ X_train + b1
A1 = relu(Z1)

Z2 = W2 @ A1 + b2
A2 = relu(Z2)

Z3 = W3 @ A2 + b3
A3 = relu(Z3)

Z4 = W4 @ A3 + b4
A4 = sigmoid(Z4)

y_hat = A4
print(y_hat.shape)  # should be (1, m)

(1, 717)

In [24]:
y_hat

,1020,479,227,910,362,967,177,884,938,499,...,214,466,121,614,20,700,71,106,270,860
0,1.0,1.0,0.999195,0.266092,0.58161,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.004094,1.0,0.620656,1.0,1.0,0.980267,1.0

In [25]:
import numpy as np

# Ensure y_train is a NumPy array and reshape to (1, m)
y_train = np.array(y_train).reshape(1, -1)
y_test = np.array(y_test).reshape(1, -1)

print("After reshape:")
print("y_train shape:", y_train.shape)
print("y_hat shape:", y_hat.shape)

After reshape:
y_train shape: (1, 717)
y_hat shape: (1, 717)

In [26]:
y_hat = np.array(y_hat, dtype=float)
y_train = np.array(y_train, dtype=float)

Cost

In [27]:
def cost(y_hat, y):
    """
    Binary cross-entropy cost
    y_hat: predicted probabilities (1, m)
    y: true labels (1, m)
    """
    m = y.shape[1]  # number of examples
    epsilon = 1e-8  # prevent log(0)

    # make sure y and y_hat are NumPy arrays
    y_hat = np.clip(y_hat, epsilon, 1 - epsilon)

    # compute cost
    losses = -(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
    cost_value = np.sum(losses) / m

    return np.squeeze(cost_value)  # ensures it's a scalar

In [28]:
print("y_hat shape:", y_hat.shape)
print("y_train shape:", y_train.shape)
print("Cost:", cost(y_hat, y_train))

y_hat shape: (1, 717)
y_train shape: (1, 717)
Cost: 7.929736652205747

In [29]:
import numpy as np

# ---------- ACTIVATION FUNCTIONS ----------
def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return (Z > 0).astype(float)

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))


# ---------- FEED FORWARD ----------
def feed_forward(A0):
    Z1 = W1 @ A0 + b1
    A1 = relu(Z1)

    Z2 = W2 @ A1 + b2
    A2 = relu(Z2)

    Z3 = W3 @ A2 + b3
    A3 = sigmoid(Z3)

    cache = {"A0": A0, "A1": A1, "A2": A2, "A3": A3, "Z1": Z1, "Z2": Z2, "Z3": Z3}
    return A3, cache


# ---------- COST FUNCTION ----------
def cost(y_hat, Y):
    m = Y.shape[1]
    epsilon = 1e-8
    loss = -(1/m) * np.sum(Y * np.log(y_hat + epsilon) + (1 - Y) * np.log(1 - y_hat + epsilon))
    return np.squeeze(loss)


# ---------- BACKPROP LAYER 3 ----------
def backprop_layer_3(y_hat, Y, m, A2, W3):
    dC_dZ3 = (1/m) * (y_hat - Y)
    dC_dW3 = dC_dZ3 @ A2.T
    dC_db3 = np.sum(dC_dZ3, axis=1, keepdims=True)
    dC_dA2 = W3.T @ dC_dZ3
    return dC_dW3, dC_db3, dC_dA2


# ---------- BACKPROP LAYER 2 ----------
def backprop_layer_2(propagator_dC_dA2, A1, A2, W2, Z2):
    dA2_dZ2 = relu_derivative(Z2)
    dC_dZ2 = propagator_dC_dA2 * dA2_dZ2
    dC_dW2 = dC_dZ2 @ A1.T
    dC_db2 = np.sum(dC_dZ2, axis=1, keepdims=True)
    dC_dA1 = W2.T @ dC_dZ2
    return dC_dW2, dC_db2, dC_dA1


# ---------- BACKPROP LAYER 1 ----------
def backprop_layer_1(propagator_dC_dA1, A1, A0, W1, Z1):
    dA1_dZ1 = relu_derivative(Z1)
    dC_dZ1 = propagator_dC_dA1 * dA1_dZ1
    dC_dW1 = dC_dZ1 @ A0.T
    dC_db1 = np.sum(dC_dZ1, axis=1, keepdims=True)
    return dC_dW1, dC_db1


# ---------- TRAIN FUNCTION ----------
def train(A0, Y, epochs=1000, alpha=0.1):
    global W1, b1, W2, b2, W3, b3
    m = Y.shape[1]
    costs = []

    for e in range(epochs):
        # 1. FEED FORWARD
        y_hat, cache = feed_forward(A0)

        # 2. COST
        error = cost(y_hat, Y)
        costs.append(error)

        # 3. BACKPROP
        dC_dW3, dC_db3, dC_dA2 = backprop_layer_3(y_hat, Y, m, cache["A2"], W3)
        dC_dW2, dC_db2, dC_dA1 = backprop_layer_2(dC_dA2, cache["A1"], cache["A2"], W2, cache["Z2"])
        dC_dW1, dC_db1 = backprop_layer_1(dC_dA1, cache["A1"], cache["A0"], W1, cache["Z1"])

        # 4. UPDATE WEIGHTS
        W3 -= alpha * dC_dW3
        b3 -= alpha * dC_db3
        W2 -= alpha * dC_dW2
        b2 -= alpha * dC_db2
        W1 -= alpha * dC_dW1
        b1 -= alpha * dC_db1

        # 5. PRINT EVERY 100 EPOCHS
        if e % 100 == 0:
            print(f"Epoch {e}: Cost = {error:.4f}")

    return costs


# ---------- ACCURACY ----------
def accuracy(X, Y):
    y_hat, _ = feed_forward(X)
    predictions = (y_hat > 0.5).astype(int)
    acc = np.mean(predictions == Y)
    return acc

In [30]:
# Assume X_train, X_test are DataFrames -> convert to NumPy
X_train_np = np.array(x_train).T  # (n_features, m)
Y_train_np = np.array(y_train).reshape(1, -1)
X_test_np = np.array(x_test).T
Y_test_np = np.array(y_test).reshape(1, -1)

# Dimensions
n_x = X_train_np.shape[0]
n_h1, n_h2, n_y = 24, 12, 1

# Weight initialization
np.random.seed(42)
W1 = np.random.randn(n_h1, n_x) * 0.01
b1 = np.zeros((n_h1, 1))
W2 = np.random.randn(n_h2, n_h1) * 0.01
b2 = np.zeros((n_h2, 1))
W3 = np.random.randn(n_y, n_h2) * 0.01
b3 = np.zeros((n_y, 1))

# Train
costs = train(X_train_np, Y_train_np, epochs=1000, alpha=0.05)

# Evaluate
train_acc = accuracy(X_train_np, Y_train_np)
test_acc = accuracy(X_test_np, Y_test_np)

print(f"✅ Training Accuracy: {train_acc*100:.2f}%")
print(f"✅ Test Accuracy: {test_acc*100:.2f}%")

Epoch 0: Cost = 0.6931
Epoch 100: Cost = 0.6919
Epoch 200: Cost = 0.6918
Epoch 300: Cost = 0.6918
Epoch 400: Cost = 0.6918
Epoch 500: Cost = 0.6917
Epoch 600: Cost = 0.6917
Epoch 700: Cost = 0.6915
Epoch 800: Cost = 0.6913
Epoch 900: Cost = 0.6905
✅ Training Accuracy: 52.58%
✅ Test Accuracy: 48.38%

In [31]:
df_encoded = pd.get_dummies(df, columns=['cp', 'restecg', 'slope', 'thal'], drop_first=False)

In [33]:
df_encoded.shape

(1025, 24)

In [59]:
df_encoded.columns

Index(['age', 'sex', 'trestbps', 'chol', 'fbs', 'thalach', 'exang', 'oldpeak',
       'ca', 'target', 'cp_0', 'cp_1', 'cp_2', 'cp_3', 'restecg_0',
       'restecg_1', 'restecg_2', 'slope_0', 'slope_1', 'slope_2', 'thal_0',
       'thal_1', 'thal_2', 'thal_3'],
      dtype='object')

In [40]:
X=df_encoded.drop('target',axis=1).values
y=df_encoded['target'].values.reshape(1,-1)

In [43]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [44]:
X.shape

(1025, 23)

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,y.T,test_size=0.3,random_state=42, shuffle=True)
print('X_train shape:',X_train.shape)
print('X_test shape:',X_test.shape)
print('Y_train shape:',Y_train.shape)
print('Y_test shape:',Y_test.shape)

X_train shape: (717, 23)
X_test shape: (308, 23)
Y_train shape: (717, 1)
Y_test shape: (308, 1)

In [49]:
X_train, X_test = X_train.T, X_test.T
Y_train, Y_test = Y_train.T, Y_test.T

In [50]:
n_x = X_train.shape[0]
n_x

23

In [52]:
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# forward propagation
Z1 = W1 @ X_train + b1
A1 = relu(Z1)

Z2 = W2 @ A1 + b2
A2 = relu(Z2)

Z3 = W3 @ A2 + b3
A3 = relu(Z3)

Z4 = W4 @ A3 + b4
A4 = sigmoid(Z4)

y_hat = A4
print(y_hat.shape)

(1, 717)

In [56]:
print("y_hat shape:", y_hat.shape)
print("y_train shape:", Y_train.shape)
print("Cost:", cost(y_hat, Y_train))

y_hat shape: (1, 717)
y_train shape: (1, 717)
Cost: 0.10724638224340556

In [55]:
def cost(y_hat, y):
    """
    Binary cross-entropy cost
    y_hat: predicted probabilities (1, m)
    y: true labels (1, m)
    """
    m = y.shape[1]  # number of examples
    epsilon = 1e-8  # prevent log(0)

    # make sure y and y_hat are NumPy arrays
    y_hat = np.clip(y_hat, epsilon, 1 - epsilon)

    # compute cost
    losses = -(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
    cost_value = np.sum(losses) / m

    return np.squeeze(cost_value)  # ensures it's a scalar

In [57]:
def backprop(Y, cache):
    m = Y.shape[1]
    A0, A1, A2, A3, A4 = cache["A0"], cache["A1"], cache["A2"], cache["A3"], cache["A4"]
    Z1, Z2, Z3 = cache["Z1"], cache["Z2"], cache["Z3"]

    dZ4 = A4 - Y
    dW4 = (1/m) * (dZ4 @ A3.T)
    db4 = (1/m) * np.sum(dZ4, axis=1, keepdims=True)

    dA3 = W4.T @ dZ4
    dZ3 = dA3 * leaky_relu_derivative(Z3)
    dW3 = (1/m) * (dZ3 @ A2.T)
    db3 = (1/m) * np.sum(dZ3, axis=1, keepdims=True)

    dA2 = W3.T @ dZ3
    dZ2 = dA2 * leaky_relu_derivative(Z2)
    dW2 = (1/m) * (dZ2 @ A1.T)
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

    dA1 = W2.T @ dZ2
    dZ1 = dA1 * leaky_relu_derivative(Z1)
    dW1 = (1/m) * (dZ1 @ A0.T)
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

    grads = {"dW4": dW4, "db4": db4,
             "dW3": dW3, "db3": db3,
             "dW2": dW2, "db2": db2,
             "dW1": dW1, "db1": db1}

    return grads

In [58]:
def train(X, Y, epochs=2000, alpha=0.01):
    global W1, W2, W3, W4, b1, b2, b3, b4
    costs = []

    for e in range(epochs):
        y_hat, cache = feed_forward(X)
        loss = cost(y_hat, Y)
        grads = backprop(Y, cache)

        # Gradient descent update
        W1 -= alpha * grads["dW1"]
        b1 -= alpha * grads["db1"]
        W2 -= alpha * grads["dW2"]
        b2 -= alpha * grads["db2"]
        W3 -= alpha * grads["dW3"]
        b3 -= alpha * grads["db3"]
        W4 -= alpha * grads["dW4"]
        b4 -= alpha * grads["db4"]

        if e % 100 == 0:
            acc = accuracy(y_hat, Y)
            print(f"Epoch {e}: Cost = {loss:.4f}, Train Accuracy = {acc:.2f}%")
        costs.append(loss)

    return costs

# --------------------------------
# 7. Train and Evaluate
# --------------------------------
costs = train(X_train, Y_train, epochs=2000, alpha=0.01)

# Predictions
y_hat_train, _ = feed_forward(X_train)
y_hat_test, _ = feed_forward(X_test)

train_acc = accuracy(y_hat_train, Y_train)
test_acc = accuracy(y_hat_test, Y_test)

print(f"\n✅ Final Training Accuracy: {train_acc:.2f}%")
print(f"✅ Final Test Accuracy: {test_acc:.2f}%")

Epoch 0: Cost = 0.1076, Train Accuracy = 97.63%
Epoch 100: Cost = 0.1011, Train Accuracy = 97.77%
Epoch 200: Cost = 0.0951, Train Accuracy = 97.77%
Epoch 300: Cost = 0.0894, Train Accuracy = 97.77%
Epoch 400: Cost = 0.0840, Train Accuracy = 97.77%
Epoch 500: Cost = 0.0789, Train Accuracy = 98.05%
Epoch 600: Cost = 0.0742, Train Accuracy = 98.05%
Epoch 700: Cost = 0.0698, Train Accuracy = 98.05%
Epoch 800: Cost = 0.0655, Train Accuracy = 98.19%
Epoch 900: Cost = 0.0615, Train Accuracy = 98.61%
Epoch 1000: Cost = 0.0577, Train Accuracy = 98.61%
Epoch 1100: Cost = 0.0542, Train Accuracy = 98.61%
Epoch 1200: Cost = 0.0507, Train Accuracy = 98.88%
Epoch 1300: Cost = 0.0472, Train Accuracy = 99.30%
Epoch 1400: Cost = 0.0438, Train Accuracy = 99.30%
Epoch 1500: Cost = 0.0407, Train Accuracy = 99.30%
Epoch 1600: Cost = 0.0379, Train Accuracy = 99.58%
Epoch 1700: Cost = 0.0354, Train Accuracy = 99.58%
Epoch 1800: Cost = 0.0331, Train Accuracy = 99.58%
Epoch 1900: Cost = 0.0310, Train Accuracy = 99.58%

✅ Final Training Accuracy: 99.58%
✅ Final Test Accuracy: 96.75%

In [32]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# --------------------------------
# 1. Load and preprocess the data
# --------------------------------
# Assume df is already loaded, e.g.:
# df = pd.read_csv("heart.csv")

# Encode categorical columns
df_encoded = pd.get_dummies(df, columns=['cp', 'restecg', 'slope', 'thal'], drop_first=False)

# Separate input and output
X = df_encoded.drop('target', axis=1).values  # numpy array
y = df_encoded['target'].values.reshape(1, -1)  # shape (1, m)

# Normalize numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, y.T, test_size=0.3, random_state=42, shuffle=True)

# Transpose so each column is one example
X_train, X_test = X_train.T, X_test.T
Y_train, Y_test = Y_train.T, Y_test.T

# Dimensions
n_x = X_train.shape[0]
n_h1, n_h2, n_h3 = 64, 32, 16
n_y = 1
m = X_train.shape[1]

# --------------------------------
# 2. Activation & Utility Functions
# --------------------------------
def leaky_relu(Z, alpha=0.01):
    return np.where(Z > 0, Z, alpha * Z)

def leaky_relu_derivative(Z, alpha=0.01):
    dZ = np.ones_like(Z)
    dZ[Z < 0] = alpha
    return dZ

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

def sigmoid_derivative(A):
    return A * (1 - A)

def cost(y_hat, Y):
    m = Y.shape[1]
    epsilon = 1e-8
    return -(1/m) * np.sum(Y * np.log(y_hat + epsilon) + (1 - Y) * np.log(1 - y_hat + epsilon))

def accuracy(y_hat, Y):
    preds = (y_hat > 0.5).astype(int)
    return np.mean(preds == Y) * 100

# --------------------------------
# 3. Initialize weights (He init)
# --------------------------------
np.random.seed(42)
W1 = np.random.randn(n_h1, n_x) * np.sqrt(2/n_x)
b1 = np.zeros((n_h1, 1))

W2 = np.random.randn(n_h2, n_h1) * np.sqrt(2/n_h1)
b2 = np.zeros((n_h2, 1))

W3 = np.random.randn(n_h3, n_h2) * np.sqrt(2/n_h2)
b3 = np.zeros((n_h3, 1))

W4 = np.random.randn(n_y, n_h3) * np.sqrt(2/n_h3)
b4 = np.zeros((n_y, 1))

# --------------------------------
# 4. Feed Forward
# --------------------------------
def feed_forward(X):
    cache = {}

    Z1 = W1 @ X + b1
    A1 = leaky_relu(Z1)

    Z2 = W2 @ A1 + b2
    A2 = leaky_relu(Z2)

    Z3 = W3 @ A2 + b3
    A3 = leaky_relu(Z3)

    Z4 = W4 @ A3 + b4
    A4 = sigmoid(Z4)

    cache = {"A0": X, "Z1": Z1, "A1": A1,
              "Z2": Z2, "A2": A2, "Z3": Z3, "A3": A3,
              "Z4": Z4, "A4": A4}

    return A4, cache

# --------------------------------
# 5. Backpropagation
# --------------------------------
def backprop(Y, cache):
    m = Y.shape[1]
    A0, A1, A2, A3, A4 = cache["A0"], cache["A1"], cache["A2"], cache["A3"], cache["A4"]
    Z1, Z2, Z3 = cache["Z1"], cache["Z2"], cache["Z3"]

    dZ4 = A4 - Y
    dW4 = (1/m) * (dZ4 @ A3.T)
    db4 = (1/m) * np.sum(dZ4, axis=1, keepdims=True)

    dA3 = W4.T @ dZ4
    dZ3 = dA3 * leaky_relu_derivative(Z3)
    dW3 = (1/m) * (dZ3 @ A2.T)
    db3 = (1/m) * np.sum(dZ3, axis=1, keepdims=True)

    dA2 = W3.T @ dZ3
    dZ2 = dA2 * leaky_relu_derivative(Z2)
    dW2 = (1/m) * (dZ2 @ A1.T)
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

    dA1 = W2.T @ dZ2
    dZ1 = dA1 * leaky_relu_derivative(Z1)
    dW1 = (1/m) * (dZ1 @ A0.T)
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

    grads = {"dW4": dW4, "db4": db4,
             "dW3": dW3, "db3": db3,
             "dW2": dW2, "db2": db2,
             "dW1": dW1, "db1": db1}

    return grads

# --------------------------------
# 6. Training function
# --------------------------------
def train(X, Y, epochs=2000, alpha=0.01):
    global W1, W2, W3, W4, b1, b2, b3, b4
    costs = []

    for e in range(epochs):
        y_hat, cache = feed_forward(X)
        loss = cost(y_hat, Y)
        grads = backprop(Y, cache)

        # Gradient descent update
        W1 -= alpha * grads["dW1"]
        b1 -= alpha * grads["db1"]
        W2 -= alpha * grads["dW2"]
        b2 -= alpha * grads["db2"]
        W3 -= alpha * grads["dW3"]
        b3 -= alpha * grads["db3"]
        W4 -= alpha * grads["dW4"]
        b4 -= alpha * grads["db4"]

        if e % 100 == 0:
            acc = accuracy(y_hat, Y)
            print(f"Epoch {e}: Cost = {loss:.4f}, Train Accuracy = {acc:.2f}%")
        costs.append(loss)

    return costs

# --------------------------------
# 7. Train and Evaluate
# --------------------------------
costs = train(X_train, Y_train, epochs=2000, alpha=0.01)

# Predictions
y_hat_train, _ = feed_forward(X_train)
y_hat_test, _ = feed_forward(X_test)

train_acc = accuracy(y_hat_train, Y_train)
test_acc = accuracy(y_hat_test, Y_test)

print(f"\n✅ Final Training Accuracy: {train_acc:.2f}%")
print(f"✅ Final Test Accuracy: {test_acc:.2f}%")

Epoch 0: Cost = 0.9975, Train Accuracy = 42.96%
Epoch 100: Cost = 0.4700, Train Accuracy = 82.29%
Epoch 200: Cost = 0.3773, Train Accuracy = 84.66%
Epoch 300: Cost = 0.3317, Train Accuracy = 87.45%
Epoch 400: Cost = 0.3033, Train Accuracy = 88.70%
Epoch 500: Cost = 0.2808, Train Accuracy = 89.40%
Epoch 600: Cost = 0.2615, Train Accuracy = 89.40%
Epoch 700: Cost = 0.2442, Train Accuracy = 91.77%
Epoch 800: Cost = 0.2288, Train Accuracy = 92.19%
Epoch 900: Cost = 0.2142, Train Accuracy = 92.75%
Epoch 1000: Cost = 0.2008, Train Accuracy = 94.14%
Epoch 1100: Cost = 0.1884, Train Accuracy = 95.26%
Epoch 1200: Cost = 0.1770, Train Accuracy = 95.82%
Epoch 1300: Cost = 0.1663, Train Accuracy = 96.09%
Epoch 1400: Cost = 0.1560, Train Accuracy = 96.09%
Epoch 1500: Cost = 0.1464, Train Accuracy = 96.09%
Epoch 1600: Cost = 0.1376, Train Accuracy = 96.37%
Epoch 1700: Cost = 0.1293, Train Accuracy = 96.51%
Epoch 1800: Cost = 0.1216, Train Accuracy = 97.21%
Epoch 1900: Cost = 0.1144, Train Accuracy = 97.21%

✅ Final Training Accuracy: 97.63%
✅ Final Test Accuracy: 93.18%